import os
import pandas as pd
import torch
import torch.nn.functional as F
from flask import Flask, render_template, request, redirect, url_for, session
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from wordcloud import WordCloud
from datetime import datetime
import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet


# ======================================
# CONFIG
# ======================================
UPLOAD_FOLDER = "uploads"
STATIC_FOLDER = "static"
MODEL_PATH = "policy_sentiment_final"   # <<< NEW MODEL
USERS_DB = "users.xlsx"
HISTORY_DB = "history.xlsx"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

app = Flask(__name__)
app.secret_key = "supersecretkey123"

# ======================================
# INIT DATABASES
# ======================================
if not os.path.exists(USERS_DB):
    pd.DataFrame(columns=["username", "email", "password"]).to_excel(USERS_DB, index=False)

if not os.path.exists(HISTORY_DB):
    pd.DataFrame(columns=["username", "filename", "timestamp", "positive", "neutral", "negative", "uncertain"]).to_excel(HISTORY_DB, index=False)

# ======================================
# LOAD MODELS
# ======================================
print("Loading AI models...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, local_files_only=True)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH, local_files_only=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

LABEL_MAP = {0: "negative", 1: "neutral", 2: "positive"}

summarizer = pipeline("summarization", model="facebook/bart-large-cnn", device=0 if torch.cuda.is_available() else -1)

print("Models loaded.")

# ======================================
# HELPERS
# ======================================
def hash_password(pw):
    return hashlib.sha256(pw.encode()).hexdigest()

def generate_pdf_report(user, stats, summaries):
    path = os.path.join(STATIC_FOLDER, "report.pdf")

    doc = SimpleDocTemplate(path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("<b>MCA Policy Feedback Analysis Report</b>", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"Generated by: {user}", styles["Normal"]))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Summary Statistics</b>", styles["Heading2"]))
    story.append(Paragraph(f"Positive: {stats['positive']}%", styles["Normal"]))
    story.append(Paragraph(f"Neutral: {stats['neutral']}%", styles["Normal"]))
    story.append(Paragraph(f"Negative: {stats['negative']}%", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Summaries</b>", styles["Heading2"]))
    story.append(Paragraph("<b>Positive Feedback</b>", styles["Normal"]))
    story.append(Paragraph(summaries["pos"], styles["BodyText"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Neutral Feedback</b>", styles["Normal"]))
    story.append(Paragraph(summaries["neu"], styles["BodyText"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Negative Feedback</b>", styles["Normal"]))
    story.append(Paragraph(summaries["neg"], styles["BodyText"]))
    story.append(Spacer(1, 12))

    # Wordcloud
    wc_path = os.path.join(STATIC_FOLDER, "wordcloud.png")
    if os.path.exists(wc_path):
        story.append(Paragraph("<b>Word Cloud</b>", styles["Heading2"]))
        story.append(Image(wc_path, width=400, height=200))

    doc.build(story)
    return path


def predict_sentiment(texts):
    labels = []
    confidences = []

    for i in range(0, len(texts), 32):
        batch = texts[i:i+32]
        inputs = tokenizer(batch, padding=True, truncation=True, max_length=256, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            probs = F.softmax(outputs.logits, dim=1)

        preds = torch.argmax(probs, dim=1)

        for p, prob in zip(preds, probs):
            labels.append(LABEL_MAP[int(p)])
            confidences.append(float(prob[int(p)]))

    return labels, confidences

def generate_wordcloud(texts):
    wc = WordCloud(width=1200, height=600, background_color="white")
    wc.generate(" ".join(texts))
    wc.to_file(os.path.join(STATIC_FOLDER, "wordcloud.png"))

def summarize(texts):
    if len(texts) == 0:
        return "No comments in this category."
    joined = " ".join(texts[:20])[:3500]
    out = summarizer(joined, max_length=180, min_length=80, do_sample=False)
    return out[0]["summary_text"]

# ======================================
# AUTH
# ======================================
@app.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        users = pd.read_excel(USERS_DB)

        username = request.form["username"]
        email = request.form["email"]
        password = hash_password(request.form["password"])

        if username in users["username"].values:
            return "Username already exists!"

        users.loc[len(users)] = [username, email, password]
        users.to_excel(USERS_DB, index=False)

        return redirect(url_for("login"))

    return render_template("signup.html")

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        users = pd.read_excel(USERS_DB)

        username = request.form["username"]
        password = hash_password(request.form["password"])

        match = users[(users["username"] == username) & (users["password"] == password)]

        if len(match) == 0:
            return "Invalid login!"

        session["user"] = username
        return redirect(url_for("index"))

    return render_template("login.html")

@app.route("/logout")
def logout():
    session.pop("user", None)
    return redirect(url_for("login"))

# ======================================
# MAIN PAGES
# ======================================
@app.route("/", methods=["GET", "POST"])
def index():
    if "user" not in session:
        return redirect(url_for("login"))

    if request.method == "POST":
        file = request.files["file"]
        path = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(path)
        return redirect(url_for("analyze", filename=file.filename))

    return render_template("index.html", user=session["user"])

@app.route("/analyze/<filename>")
def analyze(filename):
    if "user" not in session:
        return redirect(url_for("login"))

    df = pd.read_csv(os.path.join(UPLOAD_FOLDER, filename))
    texts = df["comment_text"].astype(str).tolist()

    sentiments, confidences = predict_sentiment(texts)
    df["sentiment"] = sentiments
    df["confidence"] = confidences

    # Flag uncertain predictions
    df["uncertain"] = df["confidence"] < 0.6

    counts = df["sentiment"].value_counts().to_dict()
    total = len(df)
    uncertain_count = int(df["uncertain"].sum())

    percentages = {
        "positive": round(counts.get("positive",0)*100/total,2),
        "neutral": round(counts.get("neutral",0)*100/total,2),
        "negative": round(counts.get("negative",0)*100/total,2)
    }

    generate_wordcloud(texts)

    summary_pos = summarize(df[df["sentiment"]=="positive"]["comment_text"].tolist())
    summary_neu = summarize(df[df["sentiment"]=="neutral"]["comment_text"].tolist())
    summary_neg = summarize(df[df["sentiment"]=="negative"]["comment_text"].tolist())

    # Save history
    hist = pd.read_excel(HISTORY_DB)
    hist.loc[len(hist)] = [
        session["user"], filename, datetime.now().strftime("%Y-%m-%d %H:%M"),
        percentages["positive"], percentages["neutral"], percentages["negative"],
        uncertain_count
    ]
    hist.to_excel(HISTORY_DB, index=False)
    df.to_csv(os.path.join("static", "last_analysis.csv"), index=False)


    # Generate PDF
    pdf_path = generate_pdf_report(
        session["user"],
        percentages,
        {"pos": summary_pos, "neu": summary_neu, "neg": summary_neg}
    )

    return render_template(
        "dashboard.html",
        total=total,
        percentages=percentages,
        summary_pos=summary_pos,
        summary_neu=summary_neu,
        summary_neg=summary_neg,
        user=session["user"],
        uncertain=int(df["uncertain"].sum()),
        pdf_ready=True
    )


@app.route("/history")
def history():
    if "user" not in session:
        return redirect(url_for("login"))

    hist = pd.read_excel(HISTORY_DB)
    user_hist = hist[hist["username"] == session["user"]]

    return render_template("history.html", tables=user_hist.to_dict(orient="records"), user=session["user"])

# ======================================
# RUN
# ======================================
if __name__ == "__main__":
    print("====================================")
    print(" SERVER RUNNING: http://127.0.0.1:5000")
    print(" Using model: policy_sentiment_final")
    print("====================================")
    app.run(debug=True)